// Code generated by MockGen. DO NOT EDIT.
// Source: ./email_service.go
//
// Generated by this command:
//
//	mockgen -source=./email_service.go -destination=./mock/email_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SendTemplateEmail mocks base method.
func (m *MockService) SendTemplateEmail(ctx context.Context, templateName string, data any, subject string, recipients ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, templateName, data, subject}
	for _, a := range recipients {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendTemplateEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTemplateEmail indicates an expected call of SendTemplateEmail.
func (mr *MockServiceMockRecorder) SendTemplateEmail(ctx, templateName, data, subject any, recipients ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, templateName, data, subject}, recipients...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplateEmail", reflect.TypeOf((*MockService)(nil).SendTemplateEmail), varargs...)
}
