// Code generated by MockGen. DO NOT EDIT.
// Source: platform/aws/wrapper/s3.go
//
// Generated by this command:
//
//	mockgen -source=platform/aws/wrapper/s3.go -destination=platform/aws/wrapper/mock/s3_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3API is a mock of S3API interface.
type MockS3API struct {
	ctrl     *gomock.Controller
	recorder *MockS3APIMockRecorder
	isgomock struct{}
}

// MockS3APIMockRecorder is the mock recorder for MockS3API.
type MockS3APIMockRecorder struct {
	mock *MockS3API
}

// NewMockS3API creates a new mock instance.
func NewMockS3API(ctrl *gomock.Controller) *MockS3API {
	mock := &MockS3API{ctrl: ctrl}
	mock.recorder = &MockS3APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3API) EXPECT() *MockS3APIMockRecorder {
	return m.recorder
}

// HeadObject mocks base method.
func (m *MockS3API) HeadObject(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HeadObject", varargs...)
	ret0, _ := ret[0].(*s3.HeadObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockS3APIMockRecorder) HeadObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockS3API)(nil).HeadObject), varargs...)
}

// PutObject mocks base method.
func (m *MockS3API) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockS3APIMockRecorder) PutObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockS3API)(nil).PutObject), varargs...)
}

// MockS3SignedAPI is a mock of S3SignedAPI interface.
type MockS3SignedAPI struct {
	ctrl     *gomock.Controller
	recorder *MockS3SignedAPIMockRecorder
	isgomock struct{}
}

// MockS3SignedAPIMockRecorder is the mock recorder for MockS3SignedAPI.
type MockS3SignedAPIMockRecorder struct {
	mock *MockS3SignedAPI
}

// NewMockS3SignedAPI creates a new mock instance.
func NewMockS3SignedAPI(ctrl *gomock.Controller) *MockS3SignedAPI {
	mock := &MockS3SignedAPI{ctrl: ctrl}
	mock.recorder = &MockS3SignedAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3SignedAPI) EXPECT() *MockS3SignedAPIMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockS3SignedAPI) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignGetObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockS3SignedAPIMockRecorder) PresignGetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockS3SignedAPI)(nil).PresignGetObject), varargs...)
}

// MockS3APIWrapper is a mock of S3APIWrapper interface.
type MockS3APIWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockS3APIWrapperMockRecorder
	isgomock struct{}
}

// MockS3APIWrapperMockRecorder is the mock recorder for MockS3APIWrapper.
type MockS3APIWrapperMockRecorder struct {
	mock *MockS3APIWrapper
}

// NewMockS3APIWrapper creates a new mock instance.
func NewMockS3APIWrapper(ctrl *gomock.Controller) *MockS3APIWrapper {
	mock := &MockS3APIWrapper{ctrl: ctrl}
	mock.recorder = &MockS3APIWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3APIWrapper) EXPECT() *MockS3APIWrapperMockRecorder {
	return m.recorder
}

// HeadObject mocks base method.
func (m *MockS3APIWrapper) HeadObject(ctx context.Context, key string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, key)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockS3APIWrapperMockRecorder) HeadObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockS3APIWrapper)(nil).HeadObject), ctx, key)
}

// PresignGetObject mocks base method.
func (m *MockS3APIWrapper) PresignGetObject(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignGetObject", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockS3APIWrapperMockRecorder) PresignGetObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockS3APIWrapper)(nil).PresignGetObject), ctx, key)
}

// PutObject mocks base method.
func (m *MockS3APIWrapper) PutObject(ctx context.Context, key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockS3APIWrapperMockRecorder) PutObject(ctx, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockS3APIWrapper)(nil).PutObject), ctx, key, data)
}
