// Code generated by MockGen. DO NOT EDIT.
// Source: platform/aws/wrapper/ses.go
//
// Generated by this command:
//
//	mockgen -source=platform/aws/wrapper/ses.go -destination=platform/aws/wrapper/mock/ses_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sesv2 "github.com/aws/aws-sdk-go-v2/service/sesv2"
	gomock "go.uber.org/mock/gomock"
)

// MockSESAPI is a mock of SESAPI interface.
type MockSESAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSESAPIMockRecorder
	isgomock struct{}
}

// MockSESAPIMockRecorder is the mock recorder for MockSESAPI.
type MockSESAPIMockRecorder struct {
	mock *MockSESAPI
}

// NewMockSESAPI creates a new mock instance.
func NewMockSESAPI(ctrl *gomock.Controller) *MockSESAPI {
	mock := &MockSESAPI{ctrl: ctrl}
	mock.recorder = &MockSESAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSESAPI) EXPECT() *MockSESAPIMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockSESAPI) SendEmail(ctx context.Context, params *sesv2.SendEmailInput, optFns ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendEmail", varargs...)
	ret0, _ := ret[0].(*sesv2.SendEmailOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockSESAPIMockRecorder) SendEmail(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockSESAPI)(nil).SendEmail), varargs...)
}
