// Code generated by MockGen. DO NOT EDIT.
// Source: platform/aws/wrapper/xray.go
//
// Generated by this command:
//
//	mockgen -source=platform/aws/wrapper/xray.go -destination=platform/aws/wrapper/mock/xray_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
	isgomock struct{}
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// Capture mocks base method.
func (m *MockTracer) Capture(ctx context.Context, name string, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", ctx, name, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Capture indicates an expected call of Capture.
func (mr *MockTracerMockRecorder) Capture(ctx, name, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockTracer)(nil).Capture), ctx, name, fn)
}
