// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/environment/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/environment/service.go -destination=internal/modules/environment/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	environment "github.com/Luiz-Cruz/cloudforge/internal/modules/environment"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetEnvironment mocks base method.
func (m *MockService) GetEnvironment(ctx context.Context, id string) (*environment.EnvironmentState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironment", ctx, id)
	ret0, _ := ret[0].(*environment.EnvironmentState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironment indicates an expected call of GetEnvironment.
func (mr *MockServiceMockRecorder) GetEnvironment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironment", reflect.TypeOf((*MockService)(nil).GetEnvironment), ctx, id)
}

// ListEnvironments mocks base method.
func (m *MockService) ListEnvironments(ctx context.Context) ([]*environment.EnvironmentState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironments", ctx)
	ret0, _ := ret[0].([]*environment.EnvironmentState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnvironments indicates an expected call of ListEnvironments.
func (mr *MockServiceMockRecorder) ListEnvironments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironments", reflect.TypeOf((*MockService)(nil).ListEnvironments), ctx)
}

// StartProvisioning mocks base method.
func (m *MockService) StartProvisioning(ctx context.Context, name, envType string) (environment.EnvironmentState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartProvisioning", ctx, name, envType)
	ret0, _ := ret[0].(environment.EnvironmentState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartProvisioning indicates an expected call of StartProvisioning.
func (mr *MockServiceMockRecorder) StartProvisioning(ctx, name, envType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProvisioning", reflect.TypeOf((*MockService)(nil).StartProvisioning), ctx, name, envType)
}
