// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/notification/notification.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/notification/notification.go -destination=internal/services/notification/mock/notification_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// NotifyTopic mocks base method.
func (m *MockService) NotifyTopic(ctx context.Context, subject, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyTopic", ctx, subject, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyTopic indicates an expected call of NotifyTopic.
func (mr *MockServiceMockRecorder) NotifyTopic(ctx, subject, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyTopic", reflect.TypeOf((*MockService)(nil).NotifyTopic), ctx, subject, text)
}
